
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ttu.idu0080.order.server;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

import ttu.idu0080.order.server.model.EShopOrderDao;
import ttu.idu0080.order.server.model.OrderDto;

/**
 * This class was generated by Apache CXF 2.5.1 2017-02-23T13:07:27.903+02:00
 * Generated source version: 2.5.1
 * 
 */

@javax.jws.WebService(serviceName = "OrderServiceService", portName = "OrderServicePort", targetNamespace = "http://server.order.idu0080.ttu/", wsdlLocation = "file:/home/raigo/Dokumendid/veebiteenused/src/BPServer/WebContent/orders.wsdl", endpointInterface = "ttu.idu0080.order.server.OrderService")

public class OrderServiceImpl implements OrderService {

	private static final Logger LOG = Logger.getLogger(OrderServiceImpl.class.getName());

	/*
	 * (non-Javadoc)
	 * 
	 * @see ttu.idu0080.order.server.OrderService#getOrdersByCustomerId(int
	 * customerId )*
	 */
	@Override
	public List<Order> getOrdersByCustomerId(int customerId) {
		LOG.info("Executing operation getOrdersByCustomerId");
		List<Order> _return = new ArrayList<Order>();
		Order _returnVal1 = new Order();
		Customer _returnVal1Customer = new Customer();
		List<Address> _returnVal1CustomerAddresses = new ArrayList<Address>();
		_returnVal1Customer.getAddresses().addAll(_returnVal1CustomerAddresses);
		_returnVal1Customer.setCustomer(424609916);
		_returnVal1Customer.setFirstName("FirstName1629405925");
		_returnVal1Customer.setLastName("LastName1548136880");
		_returnVal1.setCustomer(_returnVal1Customer);
		_returnVal1.setOrderId(2060653549);
		List<OrderProduct> _returnVal1OrderProducts = new ArrayList<OrderProduct>();
		OrderProduct _returnVal1OrderProductsVal1 = new OrderProduct();
		_returnVal1OrderProductsVal1.setOrderProduct(965144831);
		_returnVal1OrderProductsVal1.setPrice(0.86340106f);
		_returnVal1OrderProductsVal1.setPriceTotal(0.035444856f);
		_returnVal1OrderProductsVal1.setProductCount(628876863);
		_returnVal1OrderProductsVal1.setProductName("ProductName1132552288");
		_returnVal1OrderProducts.add(_returnVal1OrderProductsVal1);
		_returnVal1.getOrderProducts().addAll(_returnVal1OrderProducts);
		_returnVal1.setPriceTotal(0.3481068f);
		Seller _returnVal1Seller = new Seller();
		List<EntAddress> _returnVal1SellerAddresses = new ArrayList<EntAddress>();
		_returnVal1Seller.getAddresses().addAll(_returnVal1SellerAddresses);
		_returnVal1Seller.setEnterprise(923132795);
		_returnVal1Seller.setName("Name2065238056");
		_returnVal1.setSeller(_returnVal1Seller);
		Address _returnVal1ShippingAddress = new Address();
		_returnVal1ShippingAddress.setAddress(-1439816631);
		_returnVal1ShippingAddress.setCountry("Country-1612850018");
		_returnVal1ShippingAddress.setCounty("County-1504244543");
		_returnVal1ShippingAddress.setStreetAddress("StreetAddress-836299840");
		_returnVal1ShippingAddress.setTownVillage("TownVillage225865658");
		_returnVal1ShippingAddress.setZipcode("Zipcode150107525");
		_returnVal1.setShippingAddress(_returnVal1ShippingAddress);
		_return.add(_returnVal1);
		return _return;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see ttu.idu0080.order.server.OrderService#getAllOrders(*
	 */
	@Override
	public java.util.List<ttu.idu0080.order.server.Order> getAllOrders() {
		LOG.info("Executing operation getAllOrders");
		try {
			java.util.List<ttu.idu0080.order.server.Order> _return = new java.util.ArrayList<ttu.idu0080.order.server.Order>();
			ttu.idu0080.order.server.Order _returnVal1 = new ttu.idu0080.order.server.Order();
			ttu.idu0080.order.server.Customer _returnVal1Customer = new ttu.idu0080.order.server.Customer();
			java.util.List<ttu.idu0080.order.server.Address> _returnVal1CustomerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.Address>();
			_returnVal1Customer.getAddresses().addAll(_returnVal1CustomerAddresses);
			_returnVal1Customer.setCustomer(-1590308556);
			_returnVal1Customer.setFirstName("FirstName-1900636466");
			_returnVal1Customer.setLastName("LastName1345163582");
			_returnVal1.setCustomer(_returnVal1Customer);
			_returnVal1.setOrderId(609272943);
			java.util.List<ttu.idu0080.order.server.OrderProduct> _returnVal1OrderProducts = new java.util.ArrayList<ttu.idu0080.order.server.OrderProduct>();
			ttu.idu0080.order.server.OrderProduct _returnVal1OrderProductsVal1 = new ttu.idu0080.order.server.OrderProduct();
			_returnVal1OrderProductsVal1.setOrderProduct(1176655859);
			_returnVal1OrderProductsVal1.setPrice(0.60602885f);
			_returnVal1OrderProductsVal1.setPriceTotal(0.86563635f);
			_returnVal1OrderProductsVal1.setProductCount(-439321721);
			_returnVal1OrderProductsVal1.setProductName("ProductName113158479");
			_returnVal1OrderProducts.add(_returnVal1OrderProductsVal1);
			_returnVal1.getOrderProducts().addAll(_returnVal1OrderProducts);
			_returnVal1.setPriceTotal(0.21271831f);
			ttu.idu0080.order.server.Seller _returnVal1Seller = new ttu.idu0080.order.server.Seller();
			java.util.List<ttu.idu0080.order.server.EntAddress> _returnVal1SellerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
			_returnVal1Seller.getAddresses().addAll(_returnVal1SellerAddresses);
			_returnVal1Seller.setEnterprise(-1607672230);
			_returnVal1Seller.setName("Name550746571");
			_returnVal1.setSeller(_returnVal1Seller);
			ttu.idu0080.order.server.Address _returnVal1ShippingAddress = new ttu.idu0080.order.server.Address();
			_returnVal1ShippingAddress.setAddress(-977991519);
			_returnVal1ShippingAddress.setCountry("Country1602794928");
			_returnVal1ShippingAddress.setCounty("County66823702");
			_returnVal1ShippingAddress.setStreetAddress("StreetAddress254991855");
			_returnVal1ShippingAddress.setTownVillage("TownVillage1254725463");
			_returnVal1ShippingAddress.setZipcode("Zipcode-1013443532");
			_returnVal1.setShippingAddress(_returnVal1ShippingAddress);
			_return.add(_returnVal1);
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see ttu.idu0080.order.server.OrderService#getOrdersByOrderId(int orderId
	 * )*
	 */
	@Override
	public ttu.idu0080.order.server.Order getOrdersByOrderId(int orderId) {
		try {
			EShopOrderDao dao = new EShopOrderDao();
			OrderDto dto = dao.getOrder(orderId);

			if (dto == null) {
				return null;
			}

			Seller seller = new Seller();
			seller.setEnterprise(dto.getSeller().getId());
			seller.setName(dto.getSeller().getName());
			seller.getAddresses().addAll(dto.getSeller().getAddresses());
			Order order = new Order();
			order.setCustomer(dto.getCustomer());
			order.setOrderId(dto.getId());
			order.setPriceTotal(dto.getPriceTotal());
			order.setSeller(seller);
			order.setShippingAddress(dto.getShippingAddress());

			return order;
		} catch (RuntimeException e) {
			e.printStackTrace();
			throw e;
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * ttu.idu0080.order.server.OrderService#getOrdersByShippingAddress(java.
	 * lang.String country ,)java.lang.String county )*
	 */
	@Override
	public java.util.List<ttu.idu0080.order.server.Order> getOrdersByShippingAddress(java.lang.String country,
			java.lang.String county) {
		LOG.info("Executing operation getOrdersByShippingAddress");
		try {
			java.util.List<ttu.idu0080.order.server.Order> _return = new java.util.ArrayList<ttu.idu0080.order.server.Order>();
			ttu.idu0080.order.server.Order _returnVal1 = new ttu.idu0080.order.server.Order();
			ttu.idu0080.order.server.Customer _returnVal1Customer = new ttu.idu0080.order.server.Customer();
			java.util.List<ttu.idu0080.order.server.Address> _returnVal1CustomerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.Address>();
			_returnVal1Customer.getAddresses().addAll(_returnVal1CustomerAddresses);
			_returnVal1Customer.setCustomer(1731991346);
			_returnVal1Customer.setFirstName("FirstName379164211");
			_returnVal1Customer.setLastName("LastName-721429038");
			_returnVal1.setCustomer(_returnVal1Customer);
			_returnVal1.setOrderId(-2110727205);
			java.util.List<ttu.idu0080.order.server.OrderProduct> _returnVal1OrderProducts = new java.util.ArrayList<ttu.idu0080.order.server.OrderProduct>();
			ttu.idu0080.order.server.OrderProduct _returnVal1OrderProductsVal1 = new ttu.idu0080.order.server.OrderProduct();
			_returnVal1OrderProductsVal1.setOrderProduct(1728464858);
			_returnVal1OrderProductsVal1.setPrice(0.8641316f);
			_returnVal1OrderProductsVal1.setPriceTotal(0.23552072f);
			_returnVal1OrderProductsVal1.setProductCount(264031053);
			_returnVal1OrderProductsVal1.setProductName("ProductName1202000037");
			_returnVal1OrderProducts.add(_returnVal1OrderProductsVal1);
			_returnVal1.getOrderProducts().addAll(_returnVal1OrderProducts);
			_returnVal1.setPriceTotal(0.7001877f);
			ttu.idu0080.order.server.Seller _returnVal1Seller = new ttu.idu0080.order.server.Seller();
			java.util.List<ttu.idu0080.order.server.EntAddress> _returnVal1SellerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
			_returnVal1Seller.getAddresses().addAll(_returnVal1SellerAddresses);
			_returnVal1Seller.setEnterprise(1430619813);
			_returnVal1Seller.setName("Name-184068529");
			_returnVal1.setSeller(_returnVal1Seller);
			ttu.idu0080.order.server.Address _returnVal1ShippingAddress = new ttu.idu0080.order.server.Address();
			_returnVal1ShippingAddress.setAddress(-1725500736);
			_returnVal1ShippingAddress.setCountry("Country-284917133");
			_returnVal1ShippingAddress.setCounty("County-248679690");
			_returnVal1ShippingAddress.setStreetAddress("StreetAddress-393793385");
			_returnVal1ShippingAddress.setTownVillage("TownVillage1809773539");
			_returnVal1ShippingAddress.setZipcode("Zipcode-2027873473");
			_returnVal1.setShippingAddress(_returnVal1ShippingAddress);
			_return.add(_returnVal1);
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * ttu.idu0080.order.server.OrderService#getOrdersByCustomerLastName(java.
	 * lang.String lastName )*
	 */
	@Override
	public java.util.List<ttu.idu0080.order.server.Order> getOrdersByCustomerLastName(java.lang.String lastName) {
		LOG.info("Executing operation getOrdersByCustomerLastName");
		try {
			java.util.List<ttu.idu0080.order.server.Order> _return = new java.util.ArrayList<ttu.idu0080.order.server.Order>();
			ttu.idu0080.order.server.Order _returnVal1 = new ttu.idu0080.order.server.Order();
			ttu.idu0080.order.server.Customer _returnVal1Customer = new ttu.idu0080.order.server.Customer();
			java.util.List<ttu.idu0080.order.server.Address> _returnVal1CustomerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.Address>();
			_returnVal1Customer.getAddresses().addAll(_returnVal1CustomerAddresses);
			_returnVal1Customer.setCustomer(1593891527);
			_returnVal1Customer.setFirstName("FirstName1211783141");
			_returnVal1Customer.setLastName("LastName372430241");
			_returnVal1.setCustomer(_returnVal1Customer);
			_returnVal1.setOrderId(1785293563);
			java.util.List<ttu.idu0080.order.server.OrderProduct> _returnVal1OrderProducts = new java.util.ArrayList<ttu.idu0080.order.server.OrderProduct>();
			ttu.idu0080.order.server.OrderProduct _returnVal1OrderProductsVal1 = new ttu.idu0080.order.server.OrderProduct();
			_returnVal1OrderProductsVal1.setOrderProduct(1790668598);
			_returnVal1OrderProductsVal1.setPrice(0.0159837f);
			_returnVal1OrderProductsVal1.setPriceTotal(0.42292678f);
			_returnVal1OrderProductsVal1.setProductCount(-868121344);
			_returnVal1OrderProductsVal1.setProductName("ProductName469119062");
			_returnVal1OrderProducts.add(_returnVal1OrderProductsVal1);
			_returnVal1.getOrderProducts().addAll(_returnVal1OrderProducts);
			_returnVal1.setPriceTotal(0.73726743f);
			ttu.idu0080.order.server.Seller _returnVal1Seller = new ttu.idu0080.order.server.Seller();
			java.util.List<ttu.idu0080.order.server.EntAddress> _returnVal1SellerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
			_returnVal1Seller.getAddresses().addAll(_returnVal1SellerAddresses);
			_returnVal1Seller.setEnterprise(2131391820);
			_returnVal1Seller.setName("Name578358177");
			_returnVal1.setSeller(_returnVal1Seller);
			ttu.idu0080.order.server.Address _returnVal1ShippingAddress = new ttu.idu0080.order.server.Address();
			_returnVal1ShippingAddress.setAddress(882352415);
			_returnVal1ShippingAddress.setCountry("Country-2145985003");
			_returnVal1ShippingAddress.setCounty("County-2145886936");
			_returnVal1ShippingAddress.setStreetAddress("StreetAddress-886129740");
			_returnVal1ShippingAddress.setTownVillage("TownVillage1472120486");
			_returnVal1ShippingAddress.setZipcode("Zipcode-660558139");
			_returnVal1.setShippingAddress(_returnVal1ShippingAddress);
			_return.add(_returnVal1);
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

}
