
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ttu.idu0080.order.server;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.5.1 2017-02-23T13:30:52+02:00
 * Generated source version: 2.5.1
 * 
 */

@javax.jws.WebService(serviceName = "OrderServiceService", portName = "OrderServicePort", targetNamespace = "http://server.order.idu0080.ttu/", wsdlLocation = "http://localhost:8080/BPServer/services/OrderServicePort?wsdl", endpointInterface = "ttu.idu0080.order.server.OrderService")

public class OrderServiceImpl implements OrderService {

	private static final Logger LOG = Logger.getLogger(OrderServiceImpl.class.getName());

	/*
	 * (non-Javadoc)
	 * 
	 * @see ttu.idu0080.order.server.OrderService#getOrdersByCustomerId(int
	 * customerId )*
	 */
	public java.util.List<ttu.idu0080.order.server.Order> getOrdersByCustomerId(int customerId) {
		LOG.info("Executing operation getOrdersByCustomerId");
		System.out.println(customerId);
		try {
			java.util.List<ttu.idu0080.order.server.Order> _return = new java.util.ArrayList<ttu.idu0080.order.server.Order>();
			ttu.idu0080.order.server.Order _returnVal1 = new ttu.idu0080.order.server.Order();
			ttu.idu0080.order.server.Customer _returnVal1Customer = new ttu.idu0080.order.server.Customer();
			java.util.List<ttu.idu0080.order.server.Address> _returnVal1CustomerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.Address>();
			_returnVal1Customer.getAddresses().addAll(_returnVal1CustomerAddresses);
			_returnVal1Customer.setCustomer(-680671291);
			_returnVal1Customer.setFirstName("FirstName218828311");
			_returnVal1Customer.setLastName("LastName1840813398");
			_returnVal1.setCustomer(_returnVal1Customer);
			_returnVal1.setOrderId(526244984);
			java.util.List<ttu.idu0080.order.server.OrderProduct> _returnVal1OrderProducts = new java.util.ArrayList<ttu.idu0080.order.server.OrderProduct>();
			ttu.idu0080.order.server.OrderProduct _returnVal1OrderProductsVal1 = new ttu.idu0080.order.server.OrderProduct();
			_returnVal1OrderProductsVal1.setOrderProduct(-752131389);
			_returnVal1OrderProductsVal1.setPrice(0.48021108f);
			_returnVal1OrderProductsVal1.setPriceTotal(0.5806052f);
			_returnVal1OrderProductsVal1.setProductCount(1447548688);
			_returnVal1OrderProductsVal1.setProductName("ProductName-555459835");
			_returnVal1OrderProducts.add(_returnVal1OrderProductsVal1);
			_returnVal1.getOrderProducts().addAll(_returnVal1OrderProducts);
			_returnVal1.setPriceTotal(0.2605517f);
			ttu.idu0080.order.server.Seller _returnVal1Seller = new ttu.idu0080.order.server.Seller();
			java.util.List<ttu.idu0080.order.server.EntAddress> _returnVal1SellerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
			_returnVal1Seller.getAddresses().addAll(_returnVal1SellerAddresses);
			_returnVal1Seller.setEnterprise(178133967);
			_returnVal1Seller.setName("Name-343061177");
			_returnVal1.setSeller(_returnVal1Seller);
			ttu.idu0080.order.server.Address _returnVal1ShippingAddress = new ttu.idu0080.order.server.Address();
			_returnVal1ShippingAddress.setAddress(2002352943);
			_returnVal1ShippingAddress.setCountry("Country-807213409");
			_returnVal1ShippingAddress.setCounty("County690771687");
			_returnVal1ShippingAddress.setStreetAddress("StreetAddress1887177146");
			_returnVal1ShippingAddress.setTownVillage("TownVillage-870549882");
			_returnVal1ShippingAddress.setZipcode("Zipcode776538346");
			_returnVal1.setShippingAddress(_returnVal1ShippingAddress);
			_return.add(_returnVal1);
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see ttu.idu0080.order.server.OrderService#getAllOrders(*
	 */
	public java.util.List<ttu.idu0080.order.server.Order> getAllOrders() {
		LOG.info("Executing operation getAllOrders");
		try {
			java.util.List<ttu.idu0080.order.server.Order> _return = new java.util.ArrayList<ttu.idu0080.order.server.Order>();
			ttu.idu0080.order.server.Order _returnVal1 = new ttu.idu0080.order.server.Order();
			ttu.idu0080.order.server.Customer _returnVal1Customer = new ttu.idu0080.order.server.Customer();
			java.util.List<ttu.idu0080.order.server.Address> _returnVal1CustomerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.Address>();
			_returnVal1Customer.getAddresses().addAll(_returnVal1CustomerAddresses);
			_returnVal1Customer.setCustomer(-11800378);
			_returnVal1Customer.setFirstName("FirstName2124987551");
			_returnVal1Customer.setLastName("LastName890276770");
			_returnVal1.setCustomer(_returnVal1Customer);
			_returnVal1.setOrderId(-1177170534);
			java.util.List<ttu.idu0080.order.server.OrderProduct> _returnVal1OrderProducts = new java.util.ArrayList<ttu.idu0080.order.server.OrderProduct>();
			ttu.idu0080.order.server.OrderProduct _returnVal1OrderProductsVal1 = new ttu.idu0080.order.server.OrderProduct();
			_returnVal1OrderProductsVal1.setOrderProduct(488047276);
			_returnVal1OrderProductsVal1.setPrice(0.5292333f);
			_returnVal1OrderProductsVal1.setPriceTotal(0.37216365f);
			_returnVal1OrderProductsVal1.setProductCount(157219284);
			_returnVal1OrderProductsVal1.setProductName("ProductName-648497005");
			_returnVal1OrderProducts.add(_returnVal1OrderProductsVal1);
			_returnVal1.getOrderProducts().addAll(_returnVal1OrderProducts);
			_returnVal1.setPriceTotal(0.83148444f);
			ttu.idu0080.order.server.Seller _returnVal1Seller = new ttu.idu0080.order.server.Seller();
			java.util.List<ttu.idu0080.order.server.EntAddress> _returnVal1SellerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
			_returnVal1Seller.getAddresses().addAll(_returnVal1SellerAddresses);
			_returnVal1Seller.setEnterprise(-1482588897);
			_returnVal1Seller.setName("Name1086252218");
			_returnVal1.setSeller(_returnVal1Seller);
			ttu.idu0080.order.server.Address _returnVal1ShippingAddress = new ttu.idu0080.order.server.Address();
			_returnVal1ShippingAddress.setAddress(-2027406460);
			_returnVal1ShippingAddress.setCountry("Country1746680408");
			_returnVal1ShippingAddress.setCounty("County336348451");
			_returnVal1ShippingAddress.setStreetAddress("StreetAddress-1106479927");
			_returnVal1ShippingAddress.setTownVillage("TownVillage-728273626");
			_returnVal1ShippingAddress.setZipcode("Zipcode-1957233006");
			_returnVal1.setShippingAddress(_returnVal1ShippingAddress);
			_return.add(_returnVal1);
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see ttu.idu0080.order.server.OrderService#getOrdersByOrderId(int orderId
	 * )*
	 */
	public ttu.idu0080.order.server.Order getOrdersByOrderId(int orderId) {
		LOG.info("Executing operation getOrdersByOrderId");
		System.out.println(orderId);
		try {
			ttu.idu0080.order.server.Order _return = new ttu.idu0080.order.server.Order();
			ttu.idu0080.order.server.Customer _returnCustomer = new ttu.idu0080.order.server.Customer();
			java.util.List<ttu.idu0080.order.server.Address> _returnCustomerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.Address>();
			ttu.idu0080.order.server.Address _returnCustomerAddressesVal1 = new ttu.idu0080.order.server.Address();
			_returnCustomerAddressesVal1.setAddress(1676941915);
			_returnCustomerAddressesVal1.setCountry("Country1787498371");
			_returnCustomerAddressesVal1.setCounty("County-178698089");
			_returnCustomerAddressesVal1.setStreetAddress("StreetAddress-1867145403");
			_returnCustomerAddressesVal1.setTownVillage("TownVillage1842390604");
			_returnCustomerAddressesVal1.setZipcode("Zipcode-1867030707");
			_returnCustomerAddresses.add(_returnCustomerAddressesVal1);
			_returnCustomer.getAddresses().addAll(_returnCustomerAddresses);
			_returnCustomer.setCustomer(1714224254);
			_returnCustomer.setFirstName("FirstName-1561885300");
			_returnCustomer.setLastName("LastName1284903491");
			_return.setCustomer(_returnCustomer);
			_return.setOrderId(-809495655);
			java.util.List<ttu.idu0080.order.server.OrderProduct> _returnOrderProducts = new java.util.ArrayList<ttu.idu0080.order.server.OrderProduct>();
			ttu.idu0080.order.server.OrderProduct _returnOrderProductsVal1 = new ttu.idu0080.order.server.OrderProduct();
			_returnOrderProductsVal1.setOrderProduct(1830294112);
			_returnOrderProductsVal1.setPrice(0.7135402f);
			_returnOrderProductsVal1.setPriceTotal(0.04920101f);
			_returnOrderProductsVal1.setProductCount(-670564537);
			_returnOrderProductsVal1.setProductName("ProductName4929331");
			_returnOrderProducts.add(_returnOrderProductsVal1);
			_return.getOrderProducts().addAll(_returnOrderProducts);
			_return.setPriceTotal(0.65175605f);
			ttu.idu0080.order.server.Seller _returnSeller = new ttu.idu0080.order.server.Seller();
			java.util.List<ttu.idu0080.order.server.EntAddress> _returnSellerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
			ttu.idu0080.order.server.EntAddress _returnSellerAddressesVal1 = new ttu.idu0080.order.server.EntAddress();
			_returnSellerAddressesVal1.setAddress(-1766339980);
			_returnSellerAddressesVal1.setCountry("Country-297715384");
			_returnSellerAddressesVal1.setCounty("County1194490160");
			_returnSellerAddressesVal1.setStreetAddress("StreetAddress-1756193073");
			_returnSellerAddressesVal1.setTownVillage("TownVillage-2114731623");
			_returnSellerAddressesVal1.setZipcode("Zipcode-1987632252");
			_returnSellerAddresses.add(_returnSellerAddressesVal1);
			_returnSeller.getAddresses().addAll(_returnSellerAddresses);
			_returnSeller.setEnterprise(1609240301);
			_returnSeller.setName("Name-1217810617");
			_return.setSeller(_returnSeller);
			ttu.idu0080.order.server.Address _returnShippingAddress = new ttu.idu0080.order.server.Address();
			_returnShippingAddress.setAddress(1644233154);
			_returnShippingAddress.setCountry("Country-1495827458");
			_returnShippingAddress.setCounty("County-1268384854");
			_returnShippingAddress.setStreetAddress("StreetAddress-155504003");
			_returnShippingAddress.setTownVillage("TownVillage-1133908478");
			_returnShippingAddress.setZipcode("Zipcode-274146252");
			_return.setShippingAddress(_returnShippingAddress);
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * ttu.idu0080.order.server.OrderService#getOrdersByShippingAddress(java.
	 * lang.String country ,)java.lang.String county )*
	 */
	public java.util.List<ttu.idu0080.order.server.Order> getOrdersByShippingAddress(java.lang.String country,
			java.lang.String county) {
		LOG.info("Executing operation getOrdersByShippingAddress");
		System.out.println(country);
		System.out.println(county);
		try {
			java.util.List<ttu.idu0080.order.server.Order> _return = new java.util.ArrayList<ttu.idu0080.order.server.Order>();
			ttu.idu0080.order.server.Order _returnVal1 = new ttu.idu0080.order.server.Order();
			ttu.idu0080.order.server.Customer _returnVal1Customer = new ttu.idu0080.order.server.Customer();
			java.util.List<ttu.idu0080.order.server.Address> _returnVal1CustomerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.Address>();
			_returnVal1Customer.getAddresses().addAll(_returnVal1CustomerAddresses);
			_returnVal1Customer.setCustomer(-954194710);
			_returnVal1Customer.setFirstName("FirstName-815750656");
			_returnVal1Customer.setLastName("LastName1483162290");
			_returnVal1.setCustomer(_returnVal1Customer);
			_returnVal1.setOrderId(-2074129717);
			java.util.List<ttu.idu0080.order.server.OrderProduct> _returnVal1OrderProducts = new java.util.ArrayList<ttu.idu0080.order.server.OrderProduct>();
			ttu.idu0080.order.server.OrderProduct _returnVal1OrderProductsVal1 = new ttu.idu0080.order.server.OrderProduct();
			_returnVal1OrderProductsVal1.setOrderProduct(-1664242363);
			_returnVal1OrderProductsVal1.setPrice(0.7927332f);
			_returnVal1OrderProductsVal1.setPriceTotal(0.40314662f);
			_returnVal1OrderProductsVal1.setProductCount(-196754581);
			_returnVal1OrderProductsVal1.setProductName("ProductName2145364092");
			_returnVal1OrderProducts.add(_returnVal1OrderProductsVal1);
			_returnVal1.getOrderProducts().addAll(_returnVal1OrderProducts);
			_returnVal1.setPriceTotal(0.23691273f);
			ttu.idu0080.order.server.Seller _returnVal1Seller = new ttu.idu0080.order.server.Seller();
			java.util.List<ttu.idu0080.order.server.EntAddress> _returnVal1SellerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
			_returnVal1Seller.getAddresses().addAll(_returnVal1SellerAddresses);
			_returnVal1Seller.setEnterprise(-2039470593);
			_returnVal1Seller.setName("Name-1514284824");
			_returnVal1.setSeller(_returnVal1Seller);
			ttu.idu0080.order.server.Address _returnVal1ShippingAddress = new ttu.idu0080.order.server.Address();
			_returnVal1ShippingAddress.setAddress(-643269426);
			_returnVal1ShippingAddress.setCountry("Country-155133801");
			_returnVal1ShippingAddress.setCounty("County-883705745");
			_returnVal1ShippingAddress.setStreetAddress("StreetAddress147117473");
			_returnVal1ShippingAddress.setTownVillage("TownVillage-464222839");
			_returnVal1ShippingAddress.setZipcode("Zipcode-1411319508");
			_returnVal1.setShippingAddress(_returnVal1ShippingAddress);
			_return.add(_returnVal1);
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * ttu.idu0080.order.server.OrderService#getOrdersByCustomerLastName(java.
	 * lang.String lastName )*
	 */
	public java.util.List<ttu.idu0080.order.server.Order> getOrdersByCustomerLastName(java.lang.String lastName) {
		LOG.info("Executing operation getOrdersByCustomerLastName");
		System.out.println(lastName);
		try {
			java.util.List<ttu.idu0080.order.server.Order> _return = new java.util.ArrayList<ttu.idu0080.order.server.Order>();
			ttu.idu0080.order.server.Order _returnVal1 = new ttu.idu0080.order.server.Order();
			ttu.idu0080.order.server.Customer _returnVal1Customer = new ttu.idu0080.order.server.Customer();
			java.util.List<ttu.idu0080.order.server.Address> _returnVal1CustomerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.Address>();
			_returnVal1Customer.getAddresses().addAll(_returnVal1CustomerAddresses);
			_returnVal1Customer.setCustomer(2139710744);
			_returnVal1Customer.setFirstName("FirstName1711275565");
			_returnVal1Customer.setLastName("LastName2117192419");
			_returnVal1.setCustomer(_returnVal1Customer);
			_returnVal1.setOrderId(-1557457107);
			java.util.List<ttu.idu0080.order.server.OrderProduct> _returnVal1OrderProducts = new java.util.ArrayList<ttu.idu0080.order.server.OrderProduct>();
			ttu.idu0080.order.server.OrderProduct _returnVal1OrderProductsVal1 = new ttu.idu0080.order.server.OrderProduct();
			_returnVal1OrderProductsVal1.setOrderProduct(-1773921809);
			_returnVal1OrderProductsVal1.setPrice(0.85729754f);
			_returnVal1OrderProductsVal1.setPriceTotal(0.949629f);
			_returnVal1OrderProductsVal1.setProductCount(1467021870);
			_returnVal1OrderProductsVal1.setProductName("ProductName-312427360");
			_returnVal1OrderProducts.add(_returnVal1OrderProductsVal1);
			_returnVal1.getOrderProducts().addAll(_returnVal1OrderProducts);
			_returnVal1.setPriceTotal(0.15729755f);
			ttu.idu0080.order.server.Seller _returnVal1Seller = new ttu.idu0080.order.server.Seller();
			java.util.List<ttu.idu0080.order.server.EntAddress> _returnVal1SellerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
			_returnVal1Seller.getAddresses().addAll(_returnVal1SellerAddresses);
			_returnVal1Seller.setEnterprise(25579640);
			_returnVal1Seller.setName("Name988573228");
			_returnVal1.setSeller(_returnVal1Seller);
			ttu.idu0080.order.server.Address _returnVal1ShippingAddress = new ttu.idu0080.order.server.Address();
			_returnVal1ShippingAddress.setAddress(1776493322);
			_returnVal1ShippingAddress.setCountry("Country-1209246752");
			_returnVal1ShippingAddress.setCounty("County654111116");
			_returnVal1ShippingAddress.setStreetAddress("StreetAddress-497304183");
			_returnVal1ShippingAddress.setTownVillage("TownVillage-597319955");
			_returnVal1ShippingAddress.setZipcode("Zipcode-11216947");
			_returnVal1.setShippingAddress(_returnVal1ShippingAddress);
			_return.add(_returnVal1);
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

}
