package localhost.raigo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-03-06T11:24:21.704+02:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://raigo.localhost/", name = "ServicesPortType")
@XmlSeeAlso({ObjectFactory.class, ttu.idu0080.order.server.ObjectFactory.class})
public interface ServicesPortType {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://raigo.localhost/services/getCouriersRequest", output = "http://raigo.localhost/services/getCouriersResponse")
    @RequestWrapper(localName = "getCouriers", targetNamespace = "http://raigo.localhost/", className = "localhost.raigo.GetCouriers")
    @WebMethod(action = "http://raigo.localhost/services/getCouriersRequest")
    @ResponseWrapper(localName = "getCouriersResponse", targetNamespace = "http://raigo.localhost/", className = "localhost.raigo.GetCouriersResponse")
    public java.util.List<localhost.raigo.Courier> getCouriers();

    @WebResult(name = "transportOffer", targetNamespace = "")
    @Action(input = "http://raigo.localhost/services/getTransportOfferRequest", output = "http://raigo.localhost/services/getTransportOfferResponse")
    @RequestWrapper(localName = "getTransportOffer", targetNamespace = "http://raigo.localhost/", className = "localhost.raigo.GetTransportOffer")
    @WebMethod(action = "http://raigo.localhost/services/getTransportOfferRequest")
    @ResponseWrapper(localName = "getTransportOfferResponse", targetNamespace = "http://raigo.localhost/", className = "localhost.raigo.GetTransportOfferResponse")
    public localhost.raigo.TransportOffer getTransportOffer(
        @WebParam(name = "courierId", targetNamespace = "")
        int courierId,
        @WebParam(name = "order", targetNamespace = "")
        ttu.idu0080.order.server.Order order
    );

    @WebResult(name = "trackingNumber", targetNamespace = "")
    @Action(input = "http://raigo.localhost/services/orderTransportRequest", output = "http://raigo.localhost/services/orderTransportResponse")
    @RequestWrapper(localName = "orderTransport", targetNamespace = "http://raigo.localhost/", className = "localhost.raigo.OrderTransport")
    @WebMethod(action = "http://raigo.localhost/services/orderTransportRequest")
    @ResponseWrapper(localName = "orderTransportResponse", targetNamespace = "http://raigo.localhost/", className = "localhost.raigo.OrderTransportResponse")
    public java.lang.String orderTransport(
        @WebParam(name = "offerId", targetNamespace = "")
        java.lang.String offerId
    );
}
