
package localhost.raigo;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.18 2017-03-06T11:24:21.648+02:00
 * Generated source version: 2.7.18
 * 
 */
public final class ServicesPortType_ServicesPort_Client {

	private static final QName SERVICE_NAME = new QName("http://raigo.localhost/", "Services");

	private ServicesPortType_ServicesPort_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = Services.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		Services ss = new Services(wsdlURL, SERVICE_NAME);
		ServicesPortType port = ss.getServicesPort();

		{
			System.out.println("Invoking getCouriers...");
			java.util.List<localhost.raigo.Courier> _getCouriers__return = port.getCouriers();
			System.out.println("getCouriers.result=" + _getCouriers__return);

		}
		{
			System.out.println("Invoking getTransportOffer...");
			int _getTransportOffer_courierId = 2022337969;
			ttu.idu0080.order.server.Order _getTransportOffer_order = new ttu.idu0080.order.server.Order();
			ttu.idu0080.order.server.Customer _getTransportOffer_orderCustomer = new ttu.idu0080.order.server.Customer();
			java.util.List<ttu.idu0080.order.server.Address> _getTransportOffer_orderCustomerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.Address>();
			ttu.idu0080.order.server.Address _getTransportOffer_orderCustomerAddressesVal1 = new ttu.idu0080.order.server.Address();
			_getTransportOffer_orderCustomerAddressesVal1.setAddress(230075959);
			_getTransportOffer_orderCustomerAddressesVal1.setCountry("Country-2109049621");
			_getTransportOffer_orderCustomerAddressesVal1.setCounty("County-575721071");
			_getTransportOffer_orderCustomerAddressesVal1.setStreetAddress("StreetAddress-401965057");
			_getTransportOffer_orderCustomerAddressesVal1.setTownVillage("TownVillage-13736703");
			_getTransportOffer_orderCustomerAddressesVal1.setZipcode("Zipcode328818173");
			_getTransportOffer_orderCustomerAddresses.add(_getTransportOffer_orderCustomerAddressesVal1);
			_getTransportOffer_orderCustomer.getAddresses().addAll(_getTransportOffer_orderCustomerAddresses);
			_getTransportOffer_orderCustomer.setCustomer(2135699496);
			_getTransportOffer_orderCustomer.setFirstName("FirstName766934339");
			_getTransportOffer_orderCustomer.setLastName("LastName-1835400360");
			_getTransportOffer_order.setCustomer(_getTransportOffer_orderCustomer);
			_getTransportOffer_order.setOrderId(2018857262);
			java.util.List<ttu.idu0080.order.server.OrderProduct> _getTransportOffer_orderOrderProducts = new java.util.ArrayList<ttu.idu0080.order.server.OrderProduct>();
			ttu.idu0080.order.server.OrderProduct _getTransportOffer_orderOrderProductsVal1 = new ttu.idu0080.order.server.OrderProduct();
			_getTransportOffer_orderOrderProductsVal1.setOrderProduct(1076155238);
			_getTransportOffer_orderOrderProductsVal1.setPrice(0.7620655f);
			_getTransportOffer_orderOrderProductsVal1.setPriceTotal(0.47960865f);
			_getTransportOffer_orderOrderProductsVal1.setProductCount(-1923287978);
			_getTransportOffer_orderOrderProductsVal1.setProductName("ProductName82448949");
			_getTransportOffer_orderOrderProducts.add(_getTransportOffer_orderOrderProductsVal1);
			_getTransportOffer_order.getOrderProducts().addAll(_getTransportOffer_orderOrderProducts);
			_getTransportOffer_order.setPriceTotal(0.0253461f);
			ttu.idu0080.order.server.Seller _getTransportOffer_orderSeller = new ttu.idu0080.order.server.Seller();
			java.util.List<ttu.idu0080.order.server.EntAddress> _getTransportOffer_orderSellerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
			ttu.idu0080.order.server.EntAddress _getTransportOffer_orderSellerAddressesVal1 = new ttu.idu0080.order.server.EntAddress();
			_getTransportOffer_orderSellerAddressesVal1.setAddress(466169182);
			_getTransportOffer_orderSellerAddressesVal1.setCountry("Country-691873213");
			_getTransportOffer_orderSellerAddressesVal1.setCounty("County1149542283");
			_getTransportOffer_orderSellerAddressesVal1.setStreetAddress("StreetAddress-996055033");
			_getTransportOffer_orderSellerAddressesVal1.setTownVillage("TownVillage-706923374");
			_getTransportOffer_orderSellerAddressesVal1.setZipcode("Zipcode113258533");
			_getTransportOffer_orderSellerAddresses.add(_getTransportOffer_orderSellerAddressesVal1);
			_getTransportOffer_orderSeller.getAddresses().addAll(_getTransportOffer_orderSellerAddresses);
			_getTransportOffer_orderSeller.setEnterprise(358651394);
			_getTransportOffer_orderSeller.setName("Name1651542668");
			_getTransportOffer_order.setSeller(_getTransportOffer_orderSeller);
			ttu.idu0080.order.server.Address _getTransportOffer_orderShippingAddress = new ttu.idu0080.order.server.Address();
			_getTransportOffer_orderShippingAddress.setAddress(-710142335);
			_getTransportOffer_orderShippingAddress.setCountry("Country1264213292");
			_getTransportOffer_orderShippingAddress.setCounty("County1838139559");
			_getTransportOffer_orderShippingAddress.setStreetAddress("StreetAddress1538733565");
			_getTransportOffer_orderShippingAddress.setTownVillage("TownVillage419655198");
			_getTransportOffer_orderShippingAddress.setZipcode("Zipcode-1731168145");
			_getTransportOffer_order.setShippingAddress(_getTransportOffer_orderShippingAddress);
			localhost.raigo.TransportOffer _getTransportOffer__return = port
					.getTransportOffer(_getTransportOffer_courierId, _getTransportOffer_order);
			System.out.println("getTransportOffer.result=" + _getTransportOffer__return);

		}
		{
			System.out.println("Invoking orderTransport...");
			java.lang.String _orderTransport_offerId = "_orderTransport_offerId-1853895407";
			java.lang.String _orderTransport__return = port.orderTransport(_orderTransport_offerId);
			System.out.println("orderTransport.result=" + _orderTransport__return);

		}

		System.exit(0);
	}

}
