
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ttu.idu0080.order.server;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.7.18 2017-03-06T16:24:26.039+02:00
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(serviceName = "CourierServiceService", portName = "CourierServicePort", targetNamespace = "http://server.order.idu0080.ttu/", wsdlLocation = "http://localhost:8080/BPServer/services/CourierServicePort?wsdl", endpointInterface = "ttu.idu0080.order.server.CourierService")

public class CourierServiceImpl implements CourierService {

	private static final Logger LOG = Logger.getLogger(CourierServiceImpl.class.getName());

	/*
	 * (non-Javadoc)
	 * 
	 * @see ttu.idu0080.order.server.CourierService#getAllCouriers(*
	 */
	public java.util.List<ttu.idu0080.order.server.Courier> getAllCouriers() {
		LOG.info("Executing operation getAllCouriers");
		try {
			java.util.List<ttu.idu0080.order.server.Courier> _return = new java.util.ArrayList<ttu.idu0080.order.server.Courier>();
			ttu.idu0080.order.server.Courier _returnVal1 = new ttu.idu0080.order.server.Courier();
			java.util.List<ttu.idu0080.order.server.EntAddress> _returnVal1Addresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
			ttu.idu0080.order.server.EntAddress _returnVal1AddressesVal1 = new ttu.idu0080.order.server.EntAddress();
			_returnVal1AddressesVal1.setAddress(-2066515975);
			_returnVal1AddressesVal1.setCountry("Country-982377739");
			_returnVal1AddressesVal1.setCounty("County1547589686");
			_returnVal1AddressesVal1.setStreetAddress("StreetAddress-1642767334");
			_returnVal1AddressesVal1.setTownVillage("TownVillage434491096");
			_returnVal1AddressesVal1.setZipcode("Zipcode-1727174279");
			_returnVal1Addresses.add(_returnVal1AddressesVal1);
			_returnVal1.getAddresses().addAll(_returnVal1Addresses);
			_returnVal1.setEnterprise(963985500);
			_returnVal1.setName("Name-839287410");
			_returnVal1.setPercentFromOrder(-794296869);
			_return.add(_returnVal1);
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * ttu.idu0080.order.server.CourierService#getCouriersByAddress(java.lang.
	 * String country ,)java.lang.String county )*
	 */
	public java.util.List<ttu.idu0080.order.server.Courier> getCouriersByAddress(java.lang.String country,
			java.lang.String county) {
		LOG.info("Executing operation getCouriersByAddress");
		System.out.println(country);
		System.out.println(county);
		try {
			java.util.List<ttu.idu0080.order.server.Courier> _return = new java.util.ArrayList<ttu.idu0080.order.server.Courier>();
			ttu.idu0080.order.server.Courier _returnVal1 = new ttu.idu0080.order.server.Courier();
			java.util.List<ttu.idu0080.order.server.EntAddress> _returnVal1Addresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
			ttu.idu0080.order.server.EntAddress _returnVal1AddressesVal1 = new ttu.idu0080.order.server.EntAddress();
			_returnVal1AddressesVal1.setAddress(-167775834);
			_returnVal1AddressesVal1.setCountry("Country532870175");
			_returnVal1AddressesVal1.setCounty("County-1675344745");
			_returnVal1AddressesVal1.setStreetAddress("StreetAddress381701771");
			_returnVal1AddressesVal1.setTownVillage("TownVillage-590393036");
			_returnVal1AddressesVal1.setZipcode("Zipcode1591635556");
			_returnVal1Addresses.add(_returnVal1AddressesVal1);
			_returnVal1.getAddresses().addAll(_returnVal1Addresses);
			_returnVal1.setEnterprise(757726803);
			_returnVal1.setName("Name-1726472641");
			_returnVal1.setPercentFromOrder(-1108621161);
			_return.add(_returnVal1);
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see ttu.idu0080.order.server.CourierService#getCourierById(int courierId
	 * )*
	 */
	public ttu.idu0080.order.server.Courier getCourierById(int courierId) {
		LOG.info("Executing operation getCourierById");
		System.out.println(courierId);
		try {
			ttu.idu0080.order.server.Courier _return = new ttu.idu0080.order.server.Courier();
			java.util.List<ttu.idu0080.order.server.EntAddress> _returnAddresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
			ttu.idu0080.order.server.EntAddress _returnAddressesVal1 = new ttu.idu0080.order.server.EntAddress();
			_returnAddressesVal1.setAddress(-25173356);
			_returnAddressesVal1.setCountry("Country-2087770523");
			_returnAddressesVal1.setCounty("County-1698298926");
			_returnAddressesVal1.setStreetAddress("StreetAddress-1288568667");
			_returnAddressesVal1.setTownVillage("TownVillage1029913448");
			_returnAddressesVal1.setZipcode("Zipcode-1791303872");
			_returnAddresses.add(_returnAddressesVal1);
			_return.getAddresses().addAll(_returnAddresses);
			_return.setEnterprise(-980935531);
			_return.setName("Name-1374615941");
			_return.setPercentFromOrder(1173566214);
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

}
