package ttu.idu0080.order.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-03-06T16:24:26.064+02:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://server.order.idu0080.ttu/", name = "CourierService")
@XmlSeeAlso({ObjectFactory.class})
public interface CourierService {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://server.order.idu0080.ttu/CourierService/getAllCouriersRequest", output = "http://server.order.idu0080.ttu/CourierService/getAllCouriersResponse")
    @RequestWrapper(localName = "getAllCouriers", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.order.server.GetAllCouriers")
    @WebMethod
    @ResponseWrapper(localName = "getAllCouriersResponse", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.order.server.GetAllCouriersResponse")
    public java.util.List<ttu.idu0080.order.server.Courier> getAllCouriers();

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://server.order.idu0080.ttu/CourierService/getCouriersByAddressRequest", output = "http://server.order.idu0080.ttu/CourierService/getCouriersByAddressResponse")
    @RequestWrapper(localName = "getCouriersByAddress", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.order.server.GetCouriersByAddress")
    @WebMethod
    @ResponseWrapper(localName = "getCouriersByAddressResponse", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.order.server.GetCouriersByAddressResponse")
    public java.util.List<ttu.idu0080.order.server.Courier> getCouriersByAddress(
        @WebParam(name = "country", targetNamespace = "")
        java.lang.String country,
        @WebParam(name = "county", targetNamespace = "")
        java.lang.String county
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://server.order.idu0080.ttu/CourierService/getCourierByIdRequest", output = "http://server.order.idu0080.ttu/CourierService/getCourierByIdResponse")
    @RequestWrapper(localName = "getCourierById", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.order.server.GetCourierById")
    @WebMethod
    @ResponseWrapper(localName = "getCourierByIdResponse", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.order.server.GetCourierByIdResponse")
    public ttu.idu0080.order.server.Courier getCourierById(
        @WebParam(name = "courier_id", targetNamespace = "")
        int courierId
    );
}
