
package ttu.idu0080.order.server;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.18 2017-03-06T16:24:25.951+02:00
 * Generated source version: 2.7.18
 * 
 */
public final class CourierService_CourierServicePort_Client {

	private static final QName SERVICE_NAME = new QName("http://server.order.idu0080.ttu/", "CourierServiceService");

	private CourierService_CourierServicePort_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = CourierServiceService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		CourierServiceService ss = new CourierServiceService(wsdlURL, SERVICE_NAME);
		CourierService port = ss.getCourierServicePort();

		{
			System.out.println("Invoking getAllCouriers...");
			java.util.List<ttu.idu0080.order.server.Courier> _getAllCouriers__return = port.getAllCouriers();
			System.out.println("getAllCouriers.result=" + _getAllCouriers__return);

		}
		{
			System.out.println("Invoking getCouriersByAddress...");
			java.lang.String _getCouriersByAddress_country = "_getCouriersByAddress_country-1801807935";
			java.lang.String _getCouriersByAddress_county = "_getCouriersByAddress_county96698294";
			java.util.List<ttu.idu0080.order.server.Courier> _getCouriersByAddress__return = port
					.getCouriersByAddress(_getCouriersByAddress_country, _getCouriersByAddress_county);
			System.out.println("getCouriersByAddress.result=" + _getCouriersByAddress__return);

		}
		{
			System.out.println("Invoking getCourierById...");
			int _getCourierById_courierId = 954893731;
			ttu.idu0080.order.server.Courier _getCourierById__return = port.getCourierById(_getCourierById_courierId);
			System.out.println("getCourierById.result=" + _getCourierById__return);

		}

		System.exit(0);
	}

}
